### ISSUE TITLE
Idea for saving a link to a long script

### ISSUE THREAD

**Issue by illus0r** [doxas/twigl#16]
If the code is over 1200 symbols, it's not saving to bitly. I guess due to limitations of bitly. In this case `undefined` is saved to a clipboard.

What if go without bitly in this case? If the link can't be shortened, let's save it in full length, often it's not a problem.

Or maybe there's a sort of workaroud I'm not aware of?

Just yesterday we had a live coding session in our club and we had to code-golf to have the code saved :-)

**Comment by doxas** [comment]
Hmmm... ...... I see.
So, if bitly fails to generate a shortened URL, you can just send the unshortened URL to the clipboard.
I'll think about it. 👍

**Comment by doxas** [comment]
@illus0r 

I implemented and deployed it based on your idea.
If the shortening fails, it is copied directly to the clipboard.

thx!

**Comment by illus0r** [comment]
OMG, thank you so much!
