### ISSUE TITLE
beforeunloadでリロード事故を防ぎたい

### ISSUE THREAD

**Issue by 0b5vr** [doxas/twigl#47]
コードを書いている途中にいつもの癖でCtrl+Rを押してしまうのですが、これをするとコードが失われてしまいます。
この挙動を `beforeunload` で防ぎたいです。

`beforeunload` は一箇所使われてはいますが、これはライブを視聴中の場合のコードでしょうか？
普通にコードを書いているときは発動しません。

https://github.com/doxas/twigl/blob/5dab0324588c1c4b9996f488d6bae5463afbc54e/src/script.js#L1439

上のコードを加味すると、おそらく「コードが一度でも編集されたとき」または「配信を視聴中」に事故リロードを防ぎたそうですね。

**Comment by doxas** [comment]
@0b5vr 

言われてみると、エディター（編集者）側の心理を思えば、リロード事故防止機能はあったほうがいいですね。
なぜつけていなかったのか……

既存の、引用いただいた箇所は視聴者数の増減をなるべく正確にやりたかった、というコードな気がします。
`beforeunload` で無条件に視聴者数をデクリメントするが、もし本当に閉じるかのアラートが出た際に思いとどまった場合、デクリメントしたのに視聴し続けていることになるので閉じられなかった場合の１分後に、自動的にカウントアップする `setTimeout` を仕込んでる、ということだった気がします。

ご提案いただいたとおり、一度でも編集されている場合はそのタイミングで `beforeunload` を設定する、というのがよさそうですね。
これはわたしの方で対応できると思いますが、他に懸念点や実装上の要望などはありますでしょうか？

**Comment by 0b5vr** [comment]
いえ、方針問題ないと思います！

**Comment by doxas** [comment]
@0b5vr 

とりま対応してみたんで、twigl.app で動作見てみてください。
不具合ありましたら教えてください！

**Comment by 0b5vr** [comment]
良さそうです！修正ありがとうございます。

https://github.com/doxas/twigl/commit/51a6cd5c7a51ceb4c78b1ba0f911fafff23bbc70
