### ISSUE TITLE
Backbuffer is set to GL_NEAREST

### ISSUE THREAD

**Issue by wrightwriter** [doxas/twigl#5]
This makes it impossible to do fluid sim, reaction diffusion.
Linear or mipmap would be a good option I think, maybe even setting to default Linear/mipmap.

**Comment by doxas** [comment]
At least, that's not possible in a WebGL 1.0 environment, but what kind of platform are you envisioning?

**Comment by wrightwriter** [comment]
Oh sorry, didn't know WebGL 1.0 does not support linear. Maybe defining a new built-in texture() function which does linear interpolation would work well?

**Comment by wrightwriter** [comment]
texture() would be an emulation of how linear would work in WebGL 2

**Comment by doxas** [comment]
I'm really sorry, maybe my perception was more wrong.
I've actually set up LINEAR to try it out and it's drawing successfully!
I had a memory that seemed impossible to achieve before, but I may have mistakenly remembered it as a different phenomenon.

We'll make sure to support LINEAR in the next update!
